### ISSUE TITLE
Which slash?

### ISSUE THREAD

**Issue by breussf** [FRBNY-DSGE/SMC_Paper_Replication#2]
In line 19 of the file "specAnSchorfheideExcersise.jl" one is asked to indicate the path of SMC_DIR. Either the path input as "c::/users/...." oder with the other slash "c::\\users\..." leads to an errro message: "LoadError: syntax: "/" (or "\") is not a unary operator".
What then is the correct "operator"?
Why is it not possible to give an exact example how to change the missing elements of the file of the AnSchorfheide model.
Many thanks for any hint: Fritz

**Comment by ethanmatlin** [comment]
I think this is unrelated to our code in this repo. 

You can learn more about how to specify paths in Julia on a Windows machine online or in the Julia documentation.

See this thread for an answer: you should use two backslashes (https://discourse.julialang.org/t/how-to-change-working-directory-in-julia-with-atom/7588)
